# Generated by Django 3.2.7 on 2023-01-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230112_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Advertisement',
        ),
    ]
