# Generated by Django 3.2.7 on 2023-01-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_ads_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='img',
            field=models.ImageField(upload_to='images/ads'),
        ),
    ]
